language: python
python:
    - 2.7

env:
    - DEPS=true
    - DEPS=false

sudo: false

install:
    - travis_retry python setup.py install
    - travis_retry pip install coveralls
    - travis_retry coverage test_httpmultipart.py

script:
    - travis_retry python test_httpmultipart.py
    - travis_retry coveralls
